### ISSUE TITLE
What is app_resource_data?

### ISSUE THREAD

**Issue by phil294** [mbfoss/gnethogs#9]
What's the GStaticResource doing here / why is it necessary? https://github.com/mbfoss/gnethogs/blob/master/src/gresources.c#L10

I was startled when I saw this when checking the repo for potential malicious code (no offense). Looks scary!  :frowning:
Thanks!

**Comment by mbfoss** [comment]
Hi,

It’s been a while since I worked on this, but 
I believe that file was generated by the glib resource compiler tool, its probably not required to be on git as its regenerated on every build. I will work on removing this when I get some time. In any way you do not have to worry about malware because that file is generated by the glib and automake tools and those are trusted software

Thank you for the feedback.
Cheers

**Comment by mbfoss** [comment]
This is fixed now
The resource file is removed from git as It will be auto generated on each build (from gnethogs/ui/app.gresources.xml)
